[WIP] the subprocess are left empty... needs a fix like this  _this one works outside sbt -- again_
Not yet ready to be merged with master because SBT again breaks the classpath resulting in:
```
2015-01-08 03:04:06,667 - [ERROR] - from Remoting in NotebookServer-akka.actor.default-dispatcher-4
notebook.client.ExecuteResponse
java.lang.ClassNotFoundException: notebook.client.ExecuteResponse
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[na:1.7.0_72]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[na:1.7.0_72]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_72]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[na:1.7.0_72]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[na:1.7.0_72]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[na:1.7.0_72]
        at java.lang.Class.forName0(Native Method) ~[na:1.7.0_72]
        at java.lang.Class.forName(Class.java:274) ~[na:1.7.0_72]
        at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:625) ~[na:1.7.0_72]
        at akka.util.ClassLoaderObjectInputStream.resolveClass(ClassLoaderObjectInputStream.scala:19) ~[akka-actor_2.10-2.2.3-shaded-protobuf.jar:na]
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1612) ~[na:1.7.0_72]
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517) ~[na:1.7.0_72]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771) ~[na:1.7.0_72]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350) ~[na:1.7.0_72]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370) ~[na:1.7.0_72]
        at akka.serialization.JavaSerializer$$anonfun$1.apply(Serializer.scala:136) ~[akka-actor_2.10-2.2.3-shaded-protobuf.jar:na]
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57) ~[scala-library-2.10.4.jar:na]
        at akka.serialization.JavaSerializer.fromBinary(Serializer.scala:136) ~[akka-actor_2.10-2.2.3-shaded-protobuf.jar:na]
        at akka.serialization.Serialization$$anonfun$deserialize$1.apply(Serialization.scala:104) ~[akka-actor_2.10-2.2.3-shaded-protobuf.jar:na]
        at scala.util.Try$.apply(Try.scala:161) ~[scala-library-2.10.4.jar:na]
        at akka.serialization.Serialization.deserialize(Serialization.scala:98) ~[akka-actor_2.10-2.2.3-shaded-protobuf.jar:na]
        at akka.remote.MessageSerializer$.deserialize(MessageSerializer.scala:23) ~[akka-remote_2.10-2.2.3-shaded-protobuf.jar:na]
        at akka.remote.DefaultMessageDispatcher.payload$lzycompute$1(Endpoint.scala:55) ~[akka-remote_2.10-2.2.3-shaded-protobuf.jar:na]
        at akka.remote.DefaultMessageDispatcher.payload$1(Endpoint.scala:55) ~[akka-remote_2.10-2.2.3-shaded-protobuf.jar:na]
        at akka.remote.DefaultMessageDispatcher.dispatch(Endpoint.scala:73) ~[akka-remote_2.10-2.2.3-shaded-protobuf.jar:na]
        at akka.remote.EndpointReader$$anonfun$receive$2.applyOrElse(Endpoint.scala:764) ~[akka-remote_2.10-2.2.3-shaded-protobuf.jar:na]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498) [akka-actor_2.10-2.2.3-shaded-protobuf.jar:na]
        at akka.actor.ActorCell.invoke(ActorCell.scala:456) [akka-actor_2.10-2.2.3-shaded-protobuf.jar:na]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237) [akka-actor_2.10-2.2.3-shaded-protobuf.jar:na]
        at akka.dispatch.Mailbox.run(Mailbox.scala:219) [akka-actor_2.10-2.2.3-shaded-protobuf.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386) [akka-actor_2.10-2.2.3-shaded-protobuf.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.10.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.10.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.10.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.10.4.jar:na]
```

As we can see it's a problem when deserializing the result of a notebook's cell result (sent back over akka remote at `notebook.client.ReplCalculator#161`).
It's on the client side, apparently serializing works fine in the spawn process.
To debug we probably need to run in debug mode `play debug` and attach a debugger on port `9999`.

**IMPORTANT:**
That doesn't happen with a `dist` or `docker` run.