fix systemd in debian package
remove unused JAVA_OPTS to fix systemd start on Debian.
Error: `spark-notebook[4247]: Error: Could not find or load main class $JAVA_OPTS`